config/routes.rb
Rails.application.routes.draw do
    scope module: :api, defaults: {format: :json} do
    %w(v1).each do |version|
      namespace version.to_sym do
        resource :configuration, only: %w(show)
        resource :user_token, path: :token, only: %w(create destroy update)
        resources :users, only: %w(create update show) do
          resources :questions, only: %w(index)
          collection do
            post :forgot_password
            put :reset_password
          end
        end
      end
    end
  end

  namespace :admin do
    devise_scope :admin_user do
      get '/stats/:scope' => "stats#stats", as: :admin_stats
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, class_name: 'FormUser', :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }
  post '/signup' => 'splash#signup', as: :splash_signup
  get '/splash' => 'splash#index'
  root 'splash#index'
  get '/setup' => 'setup#index'

end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  skip_before_filter :authenticate

  def index
  end

  def signup
    if ENV['MAILCHIMP_SPLASH_SIGNUP_LIST_ID'].blank? or ENV['MAILCHIMP_API_KEY'].blank?

      @message = "The MAILCHIMP_API_KEY and MAILCHIMP_SPLASH_SIGNUP_LIST_ID environment variables need to be set for mailing list signup to work! If you don't want this feature, you can just remove the mailing list signup feature from app/views/splash/index.html.haml"

    else
      begin

        gb = Gibbon::Request.new(api_key: ENV['MAILCHIMP_API_KEY'])

       gb.lists(ENV['MAILCHIMP_SPLASH_SIGNUP_LIST_ID']).members.create(
         body: {
           email_address: params[:signup_email],
           status: "pending"
           }
         )

        @message = 'Thanks for signing up!'

      rescue StandardError => e
        @error = true

        if e.message =~ /is already subscribed to the list/
          @message = "You're already signed up to receive updates. Thanks for your enthusiasm!"
        else
          @message = "Oops! Looks like we ran into an error. How embarrassing. Please try again later!"
        end

      end
    end
  end


  private

    def gem_available?(name)
       Gem::Specification.find_by_name(name)
    rescue Gem::LoadError
       false
    rescue
       Gem.available?(name)
    end

end

app/views/splash/_environment_checks.html.haml
%ul.list-group

  - if ENV['AWS_ACCESS_KEY_ID'].blank? or ENV['AWS_SECRET_ACCESS_KEY'].blank?
    %li.list-group-item.list-group-item-danger
      %h4 AWS
      You haven't set up your AWS account in this environment! Set the <code>AWS_ACCESS_KEY_ID</code> and <code>AWS_SECRET_ACCESS_KEY</code> environment variables to configure AWS. You should have the client sign up and follow the instructions below.
  - else
    %li.list-group-item.list-group-item-success
      %h4 AWS
      Your AWS account is configured for this environment!



  - if ENV['GOOGLE_ANALYTICS_SITE_ID'].blank?
    %li.list-group-item.list-group-item-danger
      %h4 Google Analytics
      You haven't set up a Google Analytics account in this environment! Set the <code>GOOGLE_ANALYTICS_SITE_ID</code> environment variables to configure Google Analytics. You should ask the client to <a href="http://google.com/analytics/" target="_blank">set up a Google Analytics account</a>.
  - else
    %li.list-group-item.list-group-item-success
      %h4 Google Analytics
      Your Google Analytics account is configured for this environment!



  - unless @tracker_gems.values.any?
    %li.list-group-item.list-group-item-danger
      %h4 Exception Tracking
      You haven't set up an exception tracker! May I recommend <a href="https://addons.heroku.com/honeybadger" target="_blank">Honeybadger</a>?
  - else
    %li.list-group-item.list-group-item-success
      %h4 Exception Tracking
      Found exception tracker gems(s):
      = @tracker_gems.select{|k,v| v}.keys.join(', ')



  - if ENV['MAILCHIMP_API_KEY'].blank?
    %li.list-group-item.list-group-item-danger
      %h4 Mailchimp
      <p>You haven't set up a Mailchimp account in this environment! Have the client create an account at <a href="http://mailchimp.com" target="_blank">mailchimp.com</a> and set the <code>MAILCHIMP_API_KEY</code> environment variables to configure Mailchimp.</p>
      <p>Once a Mailchimp account is configured, you'll need to create a list through the web interface and set the <code>MAILCHIMP_SPLASH_SIGNUP_LIST_ID</code> environment variable to the list id (ten-digit hex id visible in the List name &amp; defaults tab).</p>
  - else
    %li.list-group-item.list-group-item-success
      %h4 Mailchimp
      Your Mailchimp account is configured for this environment!

app/views/splash/index.html.haml
%section.masthead.jumbotron
  .container
    .row.text-center.bottom-border
      %h1 SPORK WRANGLER
      %h4 Magic phone technology for texting witches and warlocks.
      .col-sm-6.col-sm-offset-3
        =image_tag "https://s3.amazonaws.com/assets.happyfuncorp.com/splash-assets/phones.png", class: "hero img-responsive"

%section#about
  .container
    .row.text-center
      .col-sm-offset-1.col-sm-10
        .row
          %h2 GLUTEN FREE
          .col-sm-4.text-left
            =image_tag "https://s3.amazonaws.com/assets.happyfuncorp.com/splash-assets/pic1.jpg", class: "img-responsive"
            %h4 SPROUTS
            %p It was a humorously perilous business for both of us. For, before we proceed further, it must be said that the monkey-rope was fast at both ends; fast to Queequeg's broad canvas belt, and fast to my narrow leather one. So that for better or for worse, we two, for the time, were wedded; and should poor Queequeg sink to rise no more.
          .col-sm-4.text-left
            =image_tag "https://s3.amazonaws.com/assets.happyfuncorp.com/splash-assets/pic2.jpg", class: "img-responsive"
            %h4 COUNTER CULTURE
            %p It was a humorously perilous business for both of us. For, before we proceed further, it must be said that the monkey-rope was fast at both ends; fast to Queequeg's broad canvas belt, and fast to my narrow leather one.
          .col-sm-4.text-left
            =image_tag "https://s3.amazonaws.com/assets.happyfuncorp.com/splash-assets/pic3.jpg", class: "img-responsive"
            %h4 BIKE SANDWICH
            %p It was a humorously perilous business for both of us. For, before we proceed further, it must be said that the monkey-rope was fast at both ends; fast to Queequeg's broad canvas belt, and fast to my narrow leather one. So that for better or for worse, we two, for the time, were wedded; and should poor Queequeg sink to rise no more. Don't ya think? Kinda crazy if you ask me. But that's none of my business.

%section.divider
  .container
    .row.text-center
      .col-sm-offset-3.col-sm-6
        %hr
 
%section
  .container
    .row.text-center
      .col-sm-offset-1.col-sm-10
        .row
          %h2 HOW IT WORKS
          .col-sm-offset-1.col-sm-10.clearfix
            #carousel-example-generic.carousel.slide{ data: { ride: "carousel"} }
              %ol.carousel-indicators
                %li.active{ data: {target: "#carousel-example-generic", "slide-to" => "0" }}
                %li{ data: {target: "#carousel-example-generic", "slide-to" => "1" }}
                %li{ data: {target: "#carousel-example-generic", "slide-to" => "2" }}

              .carousel-inner{ role: "listbox" }
                .item.active
                  =image_tag "https://s3.amazonaws.com/assets.happyfuncorp.com/splash-assets/venn.png"
                .item
                  =image_tag "https://s3.amazonaws.com/assets.happyfuncorp.com/splash-assets/venn.png"
                .item
                  =image_tag "https://s3.amazonaws.com/assets.happyfuncorp.com/splash-assets/venn.png"

%section.divider
  .container
    .row.text-center
      .col-sm-offset-3.col-sm-6
        %hr

%section#team
  .container
    .row.text-center
      .col-sm-offset-1.col-sm-10
        .row
          %h2 THE TEAM
          .col-sm-offset-1.col-sm-10
            .row
              .col-md-6.text-left.clearfix
                =image_tag "https://s3.amazonaws.com/assets.happyfuncorp.com/splash-assets/avatar1.png", class: "avatar pull-left"
                %h4 Captain Wiggles
                %p Entrepreneur, self described genius, too many resources not enough ideas.
              .col-md-6.text-left.clearfix
                =image_tag "https://s3.amazonaws.com/assets.happyfuncorp.com/splash-assets/avatar2.png", class: "avatar pull-left"
                %h4 Panda Eyepatch
                %p Marketing. What’s it gonna take to get you into spork wrangler today? I mean today.
              .col-md-6.text-left.clearfix
                =image_tag "https://s3.amazonaws.com/assets.happyfuncorp.com/splash-assets/avatar3.png", class: "avatar pull-left"
                %h4 Apple Shirt
                %p Partnerships and product manufacturing. Engineering degree based on forks.
              .col-md-6.text-left
                =image_tag "https://s3.amazonaws.com/assets.happyfuncorp.com/splash-assets/avatar4.png", class: "avatar pull-left"
                %h4 Pixel Face
                %p Developer, shut in, grumpy but lovable. Technical backbone and anime lover.

%section.divider
  .container
    .row.text-center
      .col-sm-offset-3.col-sm-6
        %hr

            
%section#contact
  .container
    .row
      .col-sm-8.col-sm-offset-2
        .row.text-center
          .col-sm-10.col-sm-offset-1
            %h1 Stay connected for announcements and releases.
            = form_tag splash_signup_path, role: :form, :class=>'form-inline', :remote=>true do
              .form-group#signup
                = text_field_tag :signup_email, '',  :class=>'form-control', :placeholder=>'E-mail'
                %span.btn
                  = submit_tag 'Sign up', :class=>'btn btn-primary'
                %small#signup-message

app/views/splash/signup.js.erb
<% if @error %>
  $('#signup').addClass('has-error');
<% else %>
  $('#signup').removeClass('has-error');
  $('#signup_email').val('');
<% end %>

$('#signup-message').text("<%= j @message.html_safe %>").hide().slideDown('fast');